on:
  push:
  
  pull_request:
  
  workflow_dispatch:
  
  schedule:
    ## Run every 12 hours
    - cron:  '0 */12 * * *'
  

name: "Tcl checks"

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ubuntu-latest

    name: Tcl [${{ matrix.config.language }}]

    strategy:
      fail-fast: false

      matrix:
        config:
          - { }
          - { language: 'C'          }
          - { language: 'en_US.utf8' }
          - { language: 'et_EE.utf8' }

    env:
      LANGUAGE: ${{ matrix.config.language }}
      LC_COLLATE: ${{ matrix.config.language }}

    steps:
    - name: Assert LANGUAGE availabilities
      if: runner.os == 'Linux'
      run: |
        sudo locale-gen et_EE.utf8
        locale -a | grep "${LANGUAGE}" || { >&2 echo "ERROR: LANGUAGE=${LANGUAGE} not installed"; exit 1; }
        
    - uses: actions/checkout@v4

    - name: Install Tcl
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y tclsh
        
    - name: Session information
      run: |
        tclsh <<< "puts [info patchlevel]"
        echo "LANGUAGE: ${LANGUAGE:-<not set>}"
        echo "LC_COLLATE: ${LC_COLLATE:-<not set>}"

    - name: Check CLI
      if: runner.os != 'Windows'
      run: make check-cli/seguid-tcl
      
#    - name: Check API
#      run: make check-api/seguid-tcl
