on: [push, pull_request]

name: "Python CLI check"

permissions:
  contents: read

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install the 'seguid' Python package
      run: |
        pip install git+https://github.com/seguid/seguid-python.git
        pip install pydivsufsort

    - name: Session information
      run: |
        python --version
        python -m pip list

    - name: Check CLI
      if: runner.os != 'Windows'
      run: |
        curl -L -O https://github.com/bats-core/bats-core/archive/refs/tags/v1.10.0.tar.gz && tar xf v1.10.0.tar.gz
        curl -L -O https://github.com/bats-core/bats-support/archive/refs/tags/v0.3.0.tar.gz && tar xf v0.3.0.tar.gz
        curl -L -O https://github.com/bats-core/bats-assert/archive/refs/tags/v2.1.0.tar.gz && tar xf v2.1.0.tar.gz
        export BATS_SUPPORT_HOME=$PWD/bats-support-0.3.0
        export BATS_ASSERT_HOME=$PWD/bats-assert-2.1.0
        export PATH=$PWD/bats-core-1.10.0/bin:$PATH
        bash --version
        bats --version
        make check-cli/seguid-python
