on:
  push:
  
  pull_request:
  
  schedule:
    ## Run every 3 hours
    - cron:  '0 */3 * * *'

name: "R CLI check"

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    timeout-minutes: 15

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel'    }
          - {os: macOS-latest,   r: 'release'  }
          - {os: ubuntu-latest,  r: 'devel'    }
          - {os: ubuntu-latest,  r: 'release'  }
          - {os: ubuntu-latest,  r: 'oldrel'   }
          - {os: ubuntu-latest,  r: '4.0'      }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "sessioninfo"))
        shell: Rscript {0}

      - name: Install the 'seguid' R package
        run: |
          remotes::install_github("seguid/seguid-r", dependencies = TRUE)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check CLI
        if: runner.os != 'Windows'
        run: make check-cli/seguid-python

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
